### ISSUE TITLE
Create classes for Lilt API spec

### ISSUE THREAD

**Issue by connorguy** [lilt/lilt-python#1]
Possibly use https://generator.swagger.io/ since our docs are in swagger.

**Comment by tgallant** [comment]
https://github.com/swagger-api/swagger-codegen#homebrew

**Comment by connorguy** [comment]
@tgallant we can use the swagger editor (https://editor.swagger.io/) to generate the entire api client, but it is really messy and has a lot of noise. Gets us closer though.

[python-client-generated.zip](https://github.com/lilt/pylilt/files/4247235/python-client-generated.zip)

**Comment by tgallant** [comment]
closed by #8
