### ISSUE TITLE
Licensing for project

### ISSUE THREAD

**Issue by peterwoodworth** [lilt/lilt-python#34]
Hi, was wondering what the licensing for this project is. It would be great to know what rights we have when it comes to this software, thanks

**Comment by tgallant** [comment]
Hi @peterwoodworth let me consult with the team and we will be sure to add an appropriate license file to the repo. I will keep you in the loop when I have more info.

**Comment by peterwoodworth** [comment]
Thank you @tgallant for the very prompt response and thanks for looking into it!

**Comment by tgallant** [comment]
FYI @peterwoodworth here is a PR adding the license https://github.com/lilt/lilt-python/pull/35

I will get some internal reviews on that before merging. Once it is merged I will publish a new version of the library. Let me know if you have any questions.
